### ISSUE TITLE
panic: runtime error: index out of range [0] with length 0

### ISSUE THREAD

**Issue by invidian** [yeya24/promlinter#32]
Latest version of linter fails on this code: https://gist.github.com/invidian/ad6d2e73bfb560a589bf7e85b4775568

```
$ go run -trimpath github.com/yeya24/promlinter/cmd/promlinter@d757024 lint --strict ./internal/compressor/compressor.go
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/yeya24/promlinter.(*visitor).parseSendMetricChanExpr(0xc0001ec200, 0xc0001d4ea0)
        github.com/yeya24/promlinter@v0.1.1-0.20210918184747-d757024714a1/promlinter.go:350 +0xaaf
github.com/yeya24/promlinter.(*visitor).Visit(0x4ee238, {0x8409f8, 0xc0001d4ea0})
        github.com/yeya24/promlinter@v0.1.1-0.20210918184747-d757024714a1/promlinter.go:170 +0x4d
go/ast.Walk({0x83aa00, 0xc0001ec200}, {0x8409f8, 0xc0001d4ea0})
        go/ast/walk.go:50 +0x5f
go/ast.walkStmtList({0x83aa00, 0xc0001ec200}, {0xc000109e40, 0x1, 0x8407a0})
        go/ast/walk.go:30 +0x87
go/ast.Walk({0x83aa00, 0xc0001ec200}, {0x840408, 0xc0001d4ed0})
        go/ast/walk.go:225 +0xedf
go/ast.Walk({0x83aa00, 0xc0001ec200}, {0x840700, 0xc000109e50})
        go/ast/walk.go:98 +0x18fc
go/ast.Walk({0x83aa00, 0xc0001ec200}, {0x840458, 0xc000125880})
        go/ast/walk.go:136 +0x90b
go/ast.Walk({0x83aa00, 0xc0001ec200}, {0x840778, 0xc000109e60})
        go/ast/walk.go:211 +0x23e
go/ast.walkStmtList({0x83aa00, 0xc0001ec200}, {0xc0001c6480, 0x7, 0xc0001f7948})
        go/ast/walk.go:30 +0x87
go/ast.Walk({0x83aa00, 0xc0001ec200}, {0x840408, 0xc0001d4f00})
        go/ast/walk.go:225 +0xedf
go/ast.Walk({0x83aa00, 0xc0001ec200}, {0x8406d8, 0xc0001d4f30})
        go/ast/walk.go:346 +0x7dc
go/ast.walkDeclList({0x83aa00, 0xc0001ec200}, {0xc0001258c0, 0x4, 0xc0001c6580})
        go/ast/walk.go:36 +0x87
go/ast.Walk({0x83aa00, 0xc0001ec200}, {0x840688, 0xc0001c6580})
        go/ast/walk.go:355 +0x15c5
github.com/yeya24/promlinter.RunLint(0xc000124e80, {0xc000120440, 0x1, 0x7}, {0x1a, {0x0, 0xb0, 0x7faa3928ca68}})
        github.com/yeya24/promlinter@v0.1.1-0.20210918184747-d757024714a1/promlinter.go:125 +0x16c
main.main()
        github.com/yeya24/promlinter@v0.1.1-0.20210918184747-d757024714a1/cmd/promlinter/main.go:80 +0xe72
exit status 2
```

**Comment by yeya24** [comment]
Resolved. Thanks
